# These are supported funding model platforms

github:
  - MartinFLR
ko_fi: martinfloresdev
patreon: 
open_collective: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: 
